[package]
name = "rv_zicsr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rv32i = { path = "../../bases/rv32i" }
rvcore = { path = "../../rvcore" }
